name: food_ordering_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  sentry_flutter: ^8.10.1
  scaled_app: ^2.3.0
  flutter_animate: ^4.5.0
  material_symbols_icons: ^4.2791.1
  flutter_launcher_icons: ^0.14.1
  freezed_annotation: ^2.4.4
  freezed: ^2.5.2
  fpdart: ^1.1.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/mock_data.json

  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Black.ttf
        - asset: fonts/Urbanist-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Urbanist-Bold.ttf
          weight: 800
        - asset: fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: fonts/Urbanist-ExtraBoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Urbanist-ExtraLight.ttf
          weight: 100
          style: italic
        - asset: fonts/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Urbanist-ExtraLightItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Urbanist-Italic.ttf
          weight: 200
          style: italic
        - asset: fonts/Urbanist-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Urbanist-Light.ttf
          weight: 300
        - asset: fonts/Urbanist-Medium.ttf
          weight: 800
        - asset: fonts/Urbanist-MediumItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Urbanist-Regular.ttf
          weight: 700
        - asset: fonts/Urbanist-SemiBoldItalic.ttf
          weight: 600
        - asset: fonts/Urbanist-Thin.ttf
          weight: 200
        - asset: fonts/Urbanist-ThinItalic.ttf
          weight: 100

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/appicon.jpg"
  min_sdk_android: 21